version: 2.1

commands:
  install-engine:
    description: "Install Sonarqube scanner"
    parameters:
      engine_version:
        type: string
        default: "4.2.0.1873"
    steps:
      - run:
          name: "Install Sonarqube scanner"
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-<< parameters.engine_version >>.zip
            unzip sonar-scanner-cli-<< parameters.engine_version >>.zip


jobs:
  code-analysis:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #     - "29:40:92:a4:90:da:6e:dc:d2:62:6f:ca:ee:da:bc:2d"
      - checkout
      - install-engine
      - run:
          name: code-coverage
          command: |
            cd /home/circleci/project/
            ls -lrt /home/circleci/project/
            mvn clean verify sonar:sonar -Dsonar.projectKey=SonarQube-Project -Dsonar.projectName='SonarQube-Project' -Dsonar.host.url=http://10.24.42.90:9000 -Dsonar.token=sqp_f4c88a656a835b19d2e13818e7adaf86f44a7de2
      
workflows:
  main-workflow:
    jobs:
      - code-analysis
